diplom/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("mainApp.urls")),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon/favicon.ico'))

]

urlpatterns += staticfiles_urlpatterns()

mainApp/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.base import RedirectView, TemplateView
from django.contrib import admin
from django.urls import path, include

app_name = 'mainApp'

urlpatterns = [
    url(r'^$', views.signup_view, name='signup'),
    url(r'login*$',views.login_view,name ='login'),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon/favicon.ico')),
    # path('template/login.html', TemplateView.as_view(template_name='login.html'), name='login'),
    # path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls'))
]

tasks/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.base import RedirectView

# from .views import TaskList

urlpatterns = [
    url(r'generate/$', views.generate),
    url(r'^intro/$', views.main),
    url(r'^intro/1/taskList/$', views.taskList),
    url(r'^intro/2/taskList/$', views.taskList),
    url(r'^intro/3/taskList/$', views.taskList),
    url(r'^intro/4/taskList/$', views.createList),
    url(r'^intro/5/taskList/$', views.createList),
    url(r'^intro/6/taskList/$', views.createList),
    url(r'^intro/7/taskList/$', views.createList),
    url(r'^intro/8/taskList/$', views.createList),
    url(r'^task/(?P<task_id>\d+)$', views.getTask),
    url(r'^mistakes/(?P<task_id>\d+)$', views.getTask),
    url(r'^(?P<task_id>\d+)$', views.task),
    url(r'^task/variant/(?P<task_id>\d+)', views.addVariant_cl),
    url(r'^mistakes/variant/(?P<task_id>\d+)', views.addVariant_cl),
    url(r'^addvariant/(?P<task_id>\d+)$', views.addVariant),
    url(r'^finalPage/$', views.final),
    url(r'^statistic/$', views.statistics),
    url(r'^statistic/(?P<strategy>\d+)/$', views.statistic),
    url(r'experiment/(?P<experiment_id>\d+)$', views.experiment),
    url(r'experiment/(?P<task_id>\d+)/var/$', views.variants),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon/favicon.ico'))
]

mainApp/models.py
from django.db import models

# Create your models here.

mainApp/forms.py
from django import forms

class NameForm(forms.Form):
    your_name = forms.CharField(label="Your name", max_length=100)

mainApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('tasks/generate')
    else:
        form = UserCreationForm()
    return render(request, 'mainApp/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in user
            user = form.get_user()
            login(request, user)
            return redirect('tasks/generate')
    else:
        form = AuthenticationForm()
    return render(request, 'mainApp/login.html', {'form': form})


# Create your views here.

mainApp/templates/mainApp/login.html
{% extends "mainApp/wrapper.html" %}

{% block content %}



<h1>Log in</h1>
<form class="site-form" action = "{% url 'mainApp:login'%}" method="">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>

</form>
<a type="button" href = '/'> Sign up form</a>

{% endblock %}

mainApp/templates/mainApp/signup.html
{% extends "mainApp/wrapper.html" %}
{% block title%}
  Sign up
{%endblock%}

{% block content %}
    <h3 align="center" style="color: white">Регистрация</h3>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p style="color: white" style="text-align-all: center">
        {{ field.label_tag}}

        <br style="align-content: center">

        {{ field }}

        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
    <a type="button" href = '/login'> Login form </a>
  </form>
{% endblock %}

mainApp/templates/mainApp/wrapper.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Djangonauts</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    </head>
    <body>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

<!--<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">-->